apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --out deploy/cartpole
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: caddy
  name: caddy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --out deploy/cartpole
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/timestep-default: "true"
        io.kompose.service: caddy
    spec:
      containers:
        - image: caddy
          name: caddy
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: caddy-data
            - mountPath: /config
              name: caddy-conf
      restartPolicy: Always
      volumes:
        - name: caddy-data
          persistentVolumeClaim:
            claimName: caddy-data
        - name: caddy-conf
          persistentVolumeClaim:
            claimName: caddy-conf
status: {}
