apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --file docker-compose.yml --out timestep-ai --secrets-as-files --verbose
    kompose.image-pull-secret: regcred
    {{- with (first .Values.ingress.hosts) }}
    kompose.service.expose: {{ .host }},www.{{ .host }}
    {{- end }}
    kompose.service.expose.ingress-class-name: caddy
    kompose.version: 1.30.0 (HEAD)
    kubernetes.io/ingress.class: caddy
  creationTimestamp: null
  labels:
    io.kompose.service: caddy
  name: caddy
  namespace: default
spec:
  ingressClassName: caddy
  rules:
    {{- with (first .Values.ingress.hosts) }}
    - host: {{ .host }}
      http:
        paths:
          - backend:
              service:
                name: caddy
                port:
                  number: 2019
            path: /
            pathType: Prefix
    - host: www.{{ .host }}
      http:
        paths:
          - backend:
              service:
                name: caddy
                port:
                  number: 2019
            path: /
            pathType: Prefix
    {{- end }}
status:
  loadBalancer: {}
