apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --file docker-compose.yml --generate-network-policies --out timestep-ai --secrets-as-files --verbose
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
  namespace: default
spec:
  ports:
    - name: "8484"
      port: 8484
      targetPort: 8484
  selector:
    io.kompose.service: minio
status:
  loadBalancer: {}
