apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --file docker-compose.yml --out timestep-ai --secrets-as-files --verbose
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --file docker-compose.yml --out timestep-ai --secrets-as-files --verbose
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/timestep-default: "true"
        io.kompose.service: storage
    spec:
      containers:
        - args:
            - serve
          env:
            - name: HASURA_ENDPOINT
              value: http://graphql-engine:8080/v1
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: nhost-admin-secret
            - name: HASURA_METADATA
              value: "1"
            - name: POSTGRES_MIGRATIONS
              value: "1"
            - name: POSTGRES_MIGRATIONS_SOURCE
              value: postgres://postgres:secretpgpassword@postgres:5432/postgres?sslmode=disable
            - name: PUBLIC_URL
              value: http://localhost:1337
            - name: S3_ACCESS_KEY
              value: storage-access-key-never-use-this-value
            - name: S3_BUCKET
              value: nhost
            - name: S3_ENDPOINT
              value: http://minio:8484
            - name: S3_SECRET_KEY
              value: storage-secret-key-never-use-this-value
          image: nhost/hasura-storage:0.3.1
          name: storage
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
