apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --file docker-compose.yml --out timestep-ai --secrets-as-files --verbose
    kompose.image-pull-policy: Always
    kompose.image-pull-secret: regcred
    kompose.version: 1.30.0 (HEAD)
    rollme: '{{ randAlphaNum 5 | quote }}'
  creationTimestamp: null
  labels:
    io.kompose.service: www
  name: www
  namespace: default
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: www
status:
  loadBalancer: {}
