apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --build local --build-command helm package timestep-ai --chart --file docker-compose.yml --push-image --push-command helm push timestep-ai-0.0.1.tgz oci://registry.gitlab.com/timestep-ai/timestep --push-image-registry registry.gitlab.com --out timestep-ai --secrets-as-files --verbose
    kompose.image-pull-secret: regcred
    kompose.service.expose: timestep.local,www.timestep.local
    kompose.service.expose.ingress-class-name: caddy
    kompose.version: 1.30.0 (HEAD)
    kubernetes.io/ingress.class: caddy
  creationTimestamp: null
  labels:
    io.kompose.service: www
  name: www
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: www
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --build local --build-command helm package timestep-ai --chart --file docker-compose.yml --push-image --push-command helm push timestep-ai-0.0.1.tgz oci://registry.gitlab.com/timestep-ai/timestep --push-image-registry registry.gitlab.com --out timestep-ai --secrets-as-files --verbose
        kompose.image-pull-secret: regcred
        kompose.service.expose: timestep.local,www.timestep.local
        kompose.service.expose.ingress-class-name: caddy
        kompose.version: 1.30.0 (HEAD)
        kubernetes.io/ingress.class: caddy
      creationTimestamp: null
      labels:
        io.kompose.network/timestep-default: "true"
        io.kompose.service: www
    spec:
      containers:
        - image: registry.gitlab.com/timestep-ai/timestep/www:latest
          name: www
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
            - containerPort: 443
              hostPort: 8443
              protocol: TCP
            - containerPort: 443
              hostPort: 8443
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: caddy-data
            - mountPath: /config
              name: caddy-conf
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: caddy-data
          persistentVolumeClaim:
            claimName: caddy-data
        - name: caddy-conf
          persistentVolumeClaim:
            claimName: caddy-conf
status: {}
