repos:
  - hooks:
      - id: black
        language_version: python3.11
    repo: https://github.com/psf/black
    rev: 23.3.0
  - hooks:
      - args: ["--profile", "black", "--filter-files"]
        id: isort
        name: isort (python)
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
