default_language_version:
  python: python3.11
exclude: ^$|src/timestep/infra/imports
fail_fast: true
repos:
- hooks:
  - args:
    - --fix
    - --exit-non-zero-on-fix
    id: ruff
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.275
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 23.3.0
# - hooks:
#   - id: commitizen
#   - id: commitizen-branch
#     stages:
#     - push
#   repo: https://github.com/commitizen-tools/commitizen
#   rev: v3.6.0
