default_language_version:
  python: python3.11
exclude: ^$|src/timestep/infra/imports
fail_fast: true
repos:
- hooks:
  - args:
    - --fix
    - --exit-non-zero-on-fix
    id: ruff
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.11
# - hooks:
#   - id: black
#   repo: https://github.com/psf/black
#   rev: 23.12.1
# - hooks:
#   - id: commitizen
#   - id: commitizen-branch
#     stages:
#     - push
#   repo: https://github.com/commitizen-tools/commitizen
#   rev: 3.6.0
