# secrets:
#   kubeconfig:
#     file: ./secrets/kubeconfig
services:
  api:
    build:
      context: src/timestep/services/api
      dockerfile: Dockerfile
    command: ["poetry", "run", "uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "5000"]
    environment:
      # - PREFECT_API_URL=http://prefect-server.prefect-system.svc.cluster.local:4200/api
      - PREFECT_API_URL=http://prefect-server.default.svc.cluster.local:4200/api
    expose:
      - 5000
    image: registry.gitlab.com/timestep-ai/timestep/api:${VERSION:-latest}
    labels:
      kompose.image-pull-policy: "Always"
      kompose.image-pull-secret: "regcred"
      kompose.service.healthcheck.readiness.http_get_path: /ready
      kompose.service.healthcheck.readiness.http_get_port: 5000
      rollme: "{{ randAlphaNum 5 | quote }}"
    # secrets:
    #   - kubeconfig
  caddy:
    build:
      context: src/timestep/services/caddy
      dockerfile: Dockerfile
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    environment:
      PRIMARY_DOMAIN_NAME: ${PRIMARY_DOMAIN_NAME:-timestep.local}
    image: registry.gitlab.com/timestep-ai/timestep/caddy:${VERSION:-latest}
    labels:
      kompose.image-pull-secret: "regcred"
      kompose.service.expose: "${PRIMARY_DOMAIN_NAME:-timestep.local},www.${PRIMARY_DOMAIN_NAME:-timestep.local}"
      kompose.service.expose.ingress-class-name: "caddy"
      kubernetes.io/ingress.class: "caddy"
    ports:
      - "2019:80"
    restart: always
    volumes:
      - caddy_certs:/root/.caddy
  www:
    build:
      context: src/timestep/services/www
      dockerfile: Dockerfile
    command: ["quasar", "serve", "dist/spa", "--hostname", "0.0.0.0", "-p", "9000"]
    environment:
      GRAPHQL_URI: https://www.${PRIMARY_DOMAIN_NAME}/graphql
    expose:
      - 9000
    image: registry.gitlab.com/timestep-ai/timestep/www:${VERSION:-latest}
    labels:
      kompose.image-pull-policy: "Always"
      kompose.image-pull-secret: "regcred"
      rollme: "{{ randAlphaNum 5 | quote }}"
version: '3.8'
volumes:
  caddy_certs:
