services:
  caddy:
    # build: ./src/timestep/services/caddy
    build:
      context: ./src/timestep/services/caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: always
    volumes:
      - caddy_data:/data
      - caddy_conf:/config
version: "3.7"
volumes:
  caddy_conf:
  caddy_data:
