services:
  backend:
    build:
      context: src/timestep/services/backend
      dockerfile: Dockerfile
    image: docker.io/mschock/timestep-backend:latest
    labels:
      kompose.service.expose: "api.${PRIMARY_DOMAIN_NAME}"
      kompose.service.expose.ingress-class-name: "caddy"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: src/timestep/services/frontend
      dockerfile: Dockerfile
    image: docker.io/mschock/timestep-frontend:latest
    labels:
      kompose.service.expose: "${PRIMARY_DOMAIN_NAME}"
      kompose.service.expose.ingress-class-name: "caddy"
    ports:
      - "5000:5000"

  # virtual-kubelet-saladcloud:
  #   build:
  #     context: src/lib/virtual-kubelet-saladcloud
  #     dockerfile: docker/Dockerfile
  #   image: docker.io/mschock/virtual-kubelet-saladcloud:latest
