[GLOBAL]
pants_version = "$PANTS_VERSION"

backend_packages = [
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
]

[anonymous-telemetry]
enabled = false

[python]
# We use a narrow interpreter constraint to ensure that Python PEX'es will be executable by our
# selected Docker base image, `python:3.9`.
interpreter_constraints = ["==3.9.*"]
