apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1
  labels:
    app: example1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example1
  template:
    metadata:
      labels:
        app: example1
    spec:
      containers:
      - name: httpecho
        # image: hashicorp/http-echo
        image: caddy
        # args:
        # - "-listen=:8080"
        # - "-text=Welcome to Timestep AI!"
        ports:
        - containerPort: 80
        - containerPort: 443
