---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out deploy/rps.yaml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rps
  name: rps
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rps
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out deploy/rps.yaml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/timestep-default: "true"
        io.kompose.service: rps
    spec:
      containers:
        - image: rps
          name: rps
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: caddy-data
            - mountPath: /config
              name: caddy-conf
      restartPolicy: Always
      volumes:
        - name: caddy-data
          persistentVolumeClaim:
            claimName: caddy-data
        - name: caddy-conf
          persistentVolumeClaim:
            claimName: caddy-conf
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: caddy-data
  name: caddy-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: caddy-conf
  name: caddy-conf
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

