ingress:
  enabled: true
  hosts:
    - registry.timestep.local
  annotations:
    kubernetes.io/ingress.class: caddy
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/cluster-issuer: letsencrypt-staging
    # nginx.ingress.kubernetes.io/proxy-body-size: "30720m"
  tls:
    # - secretName: docker-registry-prod
    - secretName: docker-registry-staging
      hosts:
        - registry.timestep.local

# storage: s3

secrets:
  htpasswd: ""
  # s3:
    # accessKey: "your_space_access_key"
    # secretKey: "your_space_secret_key"

# s3:
#   region: your_space_region
#   regionEndpoint: your_space_region.digitaloceanspaces.com
#   secure: true
#   bucket: your_space_name

image:
  repository: your_dockerhub_username/registry
  tag: dev
