apiVersion: v1
kind: Service
metadata:
  annotations:
    rollme: '{{ randAlphaNum 5 | quote }}'
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: default
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
