apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    rollme: '{{ randAlphaNum 5 | quote }}'
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        # rollme: '{{ randAlphaNum 5 | quote }}'
        rollme: {{ randAlphaNum 5 | quote }}
      creationTimestamp: null
      labels:
        io.kompose.network/timestep-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - args:
            - quasar
            - serve
            - dist/spa
            - --hostname
            - 0.0.0.0
            - -p
            - "9000"
          env:
          {{- with (first .Values.ingress.hosts) }}
            - name: GRAPHQL_URI
              value: https://www.{{ .host }}/graphql
          {{- end }}
          image: registry.gitlab.com/timestep-ai/timestep/frontend:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
