apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
    # rollme: '{{ randAlphaNum 5 | quote }}'
  # creationTimestamp: null
  labels:
    app: web
  name: web
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  # strategy: {}
  template:
    metadata:
      # annotations:
        # rollme: {{ randAlphaNum 5 | quote }}
      # creationTimestamp: null
      labels:
        # io.kompose.network/timestep-default: "true"
        app: web
    spec:
      containers:
        - args:
            - poetry
            - run
            - uvicorn
            - service.main:app
            - --proxy-headers
            - --host
            - 0.0.0.0
            - --port
            - "5000"
          env:
            - name: PREFECT_API_URL
              value: http://prefect-server.default.svc.cluster.local:4200/api
          image: registry.gitlab.com/timestep-ai/timestep/web:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
# status: {}
