apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    rollme: '{{ randAlphaNum 5 | quote }}'
  creationTimestamp: null
  labels:
    io.kompose.service: web-api
  name: web-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-api
  strategy: {}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      creationTimestamp: null
      labels:
        io.kompose.network/timestep-default: "true"
        io.kompose.service: web-api
    spec:
      containers:
        - args:
            - poetry
            - run
            - uvicorn
            - service.main:app
            - --proxy-headers
            - --host
            - 0.0.0.0
            - --port
            - "5000"
          env:
            - name: PREFECT_API_URL
              value: http://prefect-server.default.svc.cluster.local:4200/api
          image: registry.gitlab.com/timestep-ai/timestep/web-api:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: web-api
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
