# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        pipx install poetry==1.8.3 # TODO: Put the version in the environment
        cp .env.example .env
        sudo apt update
        sudo apt install direnv
        direnv allow
        echo $POETRY_VIRTUALENVS_IN_PROJECT
        make
    - name: Test with pytest
      run: |
        pytest
    - name: Publish to PyPI
      uses: JRubics/poetry-publish@v2.0
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}

  verify:
    needs: build
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install timestep==12.0.1
      - name: Verify
        run: |
          python -c "import timestep; print(timestep.__version__)"
