name: Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare environment 
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          secret_keys=$(echo "$SECRETS_CONTEXT" | jq -r 'keys[]')
          var_keys=$(echo "$VARS_CONTEXT" | jq -r 'keys[]')

          for key in $secret_keys; do
            if [ "$key" != "github_token" ]; then
              lowercase_key=$(echo "$key" | tr '[:upper:]' '[:lower:]')
              secret_value=$(echo "$SECRETS_CONTEXT" | jq -r ".$key")
              echo "$secret_value" > "secrets/$lowercase_key"
            fi
          done

          for key in $var_keys; do
            var_value=$(echo "$VARS_CONTEXT" | jq -r ".$key")
            echo "$key=$var_value" >> .env
          done

      - name: Destroy
        run: |
          ./src/timestep/infra/cicd/destroy.sh
