name: "Comment a Plan on a PR"

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform CDK Diff"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version-file: '.node-version'

      # - name: blah
      #   run: |
      #     echo "blah"
      #     node -v

      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version-file: '.python-version'

      # - name: blah
      #   run: |
      #     echo "blah"
      #     python -V
      # - name: Install dependencies
      #   run: yarn install

      # - name: HashiCorp - Setup Terraform
      #   uses: hashicorp/setup-terraform@v2.0.3

      # - name: Generate module and provider bindings
      #   run: npx cdktf-cli get

      # # Remove this step if you don't have any
      # - name: Run unit tests
      #   run: yarn test

      # - name: Run Terraform CDK
      #   uses: hashicorp/terraform-cdk-action@v0.1.0
      #   with:
      #     terraformVersion: 1.3.0
      #     cdktfVersion: 0.12.2
      #     stackName: my-stack
      #     mode: plan-only
      #     terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
