- name: terraform-cdk-action
  # You may pin to the exact commit or the version.
  # uses: hashicorp/terraform-cdk-action@8165232e50bd1c54d263f4b8273b5f80bcb358f1
  uses: hashicorp/terraform-cdk-action@v0.1.27
  with:
    # The version of cdktf CLI to use
    cdktfVersion: # optional, default is 0.12.2
    # The version of terraform to use
    terraformVersion: # optional, default is 1.3.0
    # The directory to use for the project
    workingDirectory: # optional, default is ./
    # The stack to run / plan, only required when the mode is plan 'plan-only' or 'plan-and-apply'
    stackName: # optional
    # What action to take: 'synth-only', 'plan-only', 'plan-and-apply'
    mode: 
    # The terraform cloud / terraform enterprise token to use
    terraformCloudToken: # optional
    # The github token to use
    githubToken: # optional
    # Whether to comment the plan / the status on the PR
    commentOnPr: # optional, default is true
    # Whether to update comment on the PR rather than adding comment
    updateComment: # optional, default is true
