name: CI
on: push

# env:
#   # DOCKER_REGISTRY_USERNAME: ${{ vars.DOCKER_REGISTRY_USERNAME }}
#   DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Print info
#         run: |
#           echo "Docker info:"
#           docker info
#           echo "Docker buildx:"
#           docker buildx version
#           echo DOCKER_REGISTRY_USERNAME: ${{ env.DOCKER_REGISTRY_USERNAME }}

#       - uses: docker/login-action@v2
#         with:
#           registry: registry.gitlab.com
#           username: ${{ env.DOCKER_REGISTRY_USERNAME }}
#           password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

#       # - name: Build and push
#       #   uses: docker/build-push-action@v4
#       #   with:
#       #     push: true
#       #     tags: user/app:latest

#       - uses: alexellis/arkade-get@master
#         with:
#           docker-compose: latest

#       - name: Build
#         run: |
#           # docker login registry.gitlab.com
#           docker-compose build

#       - name: Push
#         run: |
#           docker-compose push

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v1
  #   - run: npm install
  #   - run: npm test

# name: "Comment a Plan on a PR"

# on: [pull_request]

env:
  CDKTF_LOG_LEVEL: WARNING
  CLOUD_INSTANCE_PROVIDER: ${{ vars.CLOUD_INSTANCE_PROVIDER }}
  DO_TOKEN: ${{ secrets.DO_TOKEN }}
  DOMAIN_NAME_REGISTRAR_PROVIDER: ${{ vars.DOMAIN_NAME_REGISTRAR_PROVIDER }}
  KUBECONTEXT: ${{ vars.KUBECONTEXT }}
  NAMECHEAP_API_KEY: ${{ secrets.NAMECHEAP_API_KEY }}
  NAMECHEAP_API_USER: ${{ secrets.NAMECHEAP_API_USER }}
  NAMECHEAP_USER_NAME: ${{ secrets.NAMECHEAP_USER_NAME }}
  # PREFECT_CLOUD_WORKSPACE: ${{ vars.PREFECT_CLOUD_WORKSPACE }}
  PRIMARY_DOMAIN_NAME: ${{ vars.PRIMARY_DOMAIN_NAME }}
  SSH_PUBLIC_KEY: ${{ vars.SSH_PUBLIC_KEY }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_HOSTNAME: ${{ vars.TF_HOSTNAME }}
  TF_ORGANIZATION: ${{ vars.TF_ORGANIZATION }}
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform CDK Diff"
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - run: |
          npm install -g cdktf-cli@0.16.3

      # - name: Install dependencies
      #   run: yarn install

      # - name: Generate module and provider bindings
      #   run: npx cdktf-cli get

      # # Remove this step if you don't have any
      # - name: Run unit tests
      #   run: yarn test

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipx
          python -m pipx ensurepath
          pipx install poetry
          poetry install
          # poetry run prefect cloud login --key ${{ secrets.PREFECT_API_KEY }} --workspace ${{ env.PREFECT_CLOUD_WORKSPACE }}
          make imports

      - uses: alexellis/arkade-get@master
        with:
          k3sup: latest

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.27
        with:
          terraformVersion: 1.3.9
          cdktfVersion: 0.16.3
          stackName: ${{ env.PRIMARY_DOMAIN_NAME }}
          mode: plan-only
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
