apiVersion: v1
kind: Service
metadata:
  # annotations:
    # rollme: '{{ randAlphaNum 5 | quote }}'
  # creationTimestamp: null
  labels:
    app: server
  name: server
  namespace: default
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - port: 9090
      name: metrics
  selector:
    app: server
# status:
#   loadBalancer: {}
