apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: caddy-certs
  name: caddy-certs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
