apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/ingress.class: caddy
  labels:
    app: caddy
  name: caddy
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      annotations:
        kubernetes.io/ingress.class: caddy
      labels:
        app: caddy
    spec:
      containers:
        - env:
          {{- with (first .Values.ingress.hosts) }}
            - name: PRIMARY_DOMAIN_NAME
              value: {{ .host }}
          {{- end }}
          image: registry.gitlab.com/timestep-ai/timestep/caddy:{{ .Chart.AppVersion }}
          name: caddy
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /home/ubuntu/.caddy
              name: caddy-certs
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: caddy-certs
          persistentVolumeClaim:
            claimName: caddy-certs
