apiVersion: v1
kind: Service
metadata:
  # annotations:
    # rollme: '{{ randAlphaNum 5 | quote }}'
  # creationTimestamp: null
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: frontend
# status:
#   loadBalancer: {}
