apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
    # rollme: '{{ randAlphaNum 5 | quote }}'
  # creationTimestamp: null
  labels:
    app: client
  name: client
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: client
  # strategy: {}
  template:
    metadata:
      # annotations:
        # rollme: {{ randAlphaNum 5 | quote }}
      # creationTimestamp: null
      labels:
        # io.kompose.network/timestep-default: "true"
        app: client
    spec:
      containers:
        # - command:
        #     - /home/ubuntu/docker-entrypoint.sh
        #     - npm
        #     - run
        #     - dev
        # - env:
          # {{- with (first .Values.ingress.hosts) }}
          #   - name: GRAPHQL_URI
          #     value: https://www.{{ .host }}/graphql
          # {{- end }}
        - envFrom:
            - configMapRef:
                name: client-config-map
            - secretRef:
                name: client-secret
          image: registry.gitlab.com/timestep-ai/timestep/client:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: client
          ports:
            - containerPort: 9000
              # hostPort: 9000
              # protocol: TCP
          # resources: {}
      imagePullSecrets:
        - name: regcred
      # restartPolicy: Always
# status: {}
