apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  serviceName: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: server-config-map
            - secretRef:
                name: server-secret
          image: registry.gitlab.com/timestep-ai/timestep/server:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
          - name: sky-pv-storage
            mountPath: /home/ubuntu/.sky
          - name: ssh-pv-storage
            mountPath: /home/ubuntu/.ssh
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: sky-pv-storage
        persistentVolumeClaim:
          claimName: sky-pv-claim
      - name: ssh-pv-storage
        persistentVolumeClaim:
          claimName: ssh-pv-claim
